version: "3.7"

secrets:
  database_password:
    file: ./secrets/.database_password
  proxy_password:
    file: ./secrets/.proxy_password  

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
services:
 
  homer:
  #  secrets:
  #    - proxy_password
    build:
      context: ./homer
      dockerfile: Dockerfile.prod
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_SEPARATOR: ${IMAGE_REPOSITORY_SEPARATOR}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
        NODE_ENV: production
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-homer-prod
    security_opt:
      - no-new-privileges:true
    privileged: true
    restart: unless-stopped     
    ports:
      - "8092:8080"
    volumes:
    #  - ./homer:/app
    #  - /app/node_modules
      - ./homer/config:/www/assets
    user: 1000:1000  
    environment:
      - INIT_ASSETS=0
    #  - UID=1000
    #  - GID=1000
    #  - CHOKIDAR_USEPULLING=true
    #  - PROXY_PASSWORD='/run/secrets/proxy_password'
    depends_on:
     - "actual"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_SEPARATOR: ${IMAGE_REPOSITORY_SEPARATOR}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}    
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-nginx-prod
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    security_opt:
      - no-new-privileges:true
    privileged: true
    ports:
      - "80:80"
    depends_on:
      - "homer"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.dev
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_SEPARATOR: ${IMAGE_REPOSITORY_SEPARATOR}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
        DISABLE_IPV6: ${DISABLE_IPV6}
    env_file:
      - .env     
    container_name: ${UNIQUE_NAMESPACE}-proxy-dev
    security_opt:
      - no-new-privileges:true
    privileged: true
    restart: unless-stopped
    ports:
      - "8080:80" # Public HTTP Port
      - "8081:81" # Admin Web Port
      - "8443:443" # Public HTTPS Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile.prod
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_SEPARATOR: ${IMAGE_REPOSITORY_SEPARATOR}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_PROD}
        MYSQL_DATABASE: ${MYSQL_DATABASE_PROD}
        MYSQL_USER: ${MYSQL_USER_PROD}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD_PROD}
    env_file:
      - .env     
    container_name: ${UNIQUE_NAMESPACE}-mysql-prod
    security_opt:
      - no-new-privileges:true
    privileged: true
    restart: unless-stopped
    ports:
      - "3306:3306"

  actual:
    build:
      context: ./actual
      dockerfile: Dockerfile.prod
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_SEPARATOR: ${IMAGE_REPOSITORY_SEPARATOR}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-actual-prod
    security_opt:
      - no-new-privileges:true
    privileged: true
    restart: unless-stopped
    ports:
      - "5006:5006"
    # volumes:
    #  - ./config:/config    
    network_mode: host

  jointjs:
    build:
      context: ./jointjs
      dockerfile: Dockerfile.prod
      args: # from env_file
        UNIQUE_NAMESPACE: ${UNIQUE_NAMESPACE}
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_SEPARATOR: ${IMAGE_REPOSITORY_SEPARATOR}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env     
    container_name: ${UNIQUE_NAMESPACE}-jointjs-prod
    security_opt:
      - no-new-privileges:true
    privileged: true
    restart: unless-stopped
    ports:
      - "6080:80" 

networks:
  proxy:
    external: true
